# -*- coding: utf-8 -*-
"""PC_exercicio3_aula3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12FhGgCHxTc-CgE1MyhQZgooOMQ0DPEAu

#Pensamento Computacional
####Aluna: Bianca Muniz
####Exercício : calculando a densidade demográfica
"""

import csv
arquivo = open("brasil.csv")
leitor = csv.DictReader(arquivo)
for registro in leitor:
  registro["densidade"] = int(registro["habitantes"])/float(registro["area"])
  print(f"O município {registro['municipio']}/{registro['estado']} possui densidade demográfica de {registro['densidade']} hab/km².")