# -*- coding: utf-8 -*-
"""PC_exercicio2_aula3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gjt2SXoZTSXDFUWhkc0q91nhUFy-0UWi

#Pensamento Computacional
### Aluna: Bianca Muniz
### Exercício 2: links do chat
"""

##Carregando os arquivos

a = open("GMT20210726-212633_Recording.txt")
b = open("GMT20210728-223542_Recording.txt")
c = open("GMT20210802-212614_Recording.txt")
d = open("GMT20210804-222232_Recording.txt")
e = open("GMT20210806-222707_Recording.txt")
f = open("GMT20210809-212840_Recording.txt")
g = open("GMT20210809-213308_Recording.txt")
h = open("GMT20210809-234715_Recording.txt")
i = open("GMT20210811-223050_Recording.txt")
j = open("GMT20210813-222825_Recording.txt")
k = open("GMT20210816-212317_Recording.txt")
l = open("GMT20210816-234945_Recording.txt")
m = open("GMT20210818-222332_Recording.txt")
n = open("GMT20210820-222253_Recording.txt")

for linha in a: #para cada linha no arquivo a
  linha = linha.strip() #Sobrescreve a variável linha, sem a quebra de linha
  partes = linha.split("\t") #Cria a variável partes, lista de strings que compõem a linha
  if "www." in linha: # Se tiver "www" na variável linha
    print(partes[2]) # exibe o segundo item da lista partes (mensagem do chat)
for linha in b:
  linha = linha.strip()
  partes = linha.split("\t")
  if "www." in linha:
    print(partes[2])
for linha in c:
  linha = linha.strip()
  partes = linha.split("\t")
  if "www." in linha:
    print(partes[2])
for linha in d:
  linha = linha.strip()
  partes = linha.split("\t")
  if "www." in linha:
    print(partes[2])
for linha in e:
  linha = linha.strip()
  partes = linha.split("\t")
  if "www." in linha:
    print(partes[2])
for linha in f:
  linha = linha.strip()
  partes = linha.split("\t")
  if "www." in linha:
    print(partes[2])
for linha in g:
  linha = linha.strip()
  partes = linha.split("\t")
  if "www." in linha:
    print(partes[2])
for linha in h:
  linha = linha.strip()
  partes = linha.split("\t")
  if "www." in linha:
    print(partes[2])
for linha in i:
  linha = linha.strip()
  partes = linha.split("\t")
  if "www." in linha:
    print(partes[2])
for linha in j:
  linha = linha.strip()
  partes = linha.split("\t")
  if "www." in linha:
    print(partes[2])
for linha in k:
  linha = linha.strip()
  partes = linha.split("\t")
  if "www." in linha:
    print(partes[2])
for linha in l:
  linha = linha.strip()
  partes = linha.split("\t")
  if "www." in linha:
    print(partes[2])
for linha in m:
  linha = linha.strip()
  partes = linha.split("\t")
  if "www." in linha:
    print(partes[2])
for linha in n:
  linha = linha.strip()
  partes = linha.split("\t")
  if "www." in linha:
    print(partes[2])